footer
LenaXmi/calc-2-fantasticFour- pull request #3
Opened 2021-07-06 19:20 UTC by Halishchev

footer

2021-07-06 23:49 UTC, DimaLitvinenko commented on src/sass/layout/_footer.scss
> +    transition: color $animation;
transition нужно прописать на сам элемент а не в ховер фокус

2021-07-06 23:54 UTC, DimaLitvinenko commented on src/sass/layout/_footer.scss
> +    transition: color $animation;
Transition нужно прописывать на элемент (ссылку) а не в ховер и фокус

2021-07-06 23:55 UTC, DimaLitvinenko requested changes

2021-07-06 23:55 UTC, DimaLitvinenko commented on src/sass/layout/_footer.scss
> +    transition: color $animation;
Transition нужно прописывать на элемент (ссылку) а не в ховер и фокус

2021-07-07 01:59 UTC, LenaXmi requested changes

2021-07-07 01:59 UTC, LenaXmi commented on src/sass/layout/_footer.scss
> +  @media screen and (max-width: 460px) {
А почему ширина 460, а не 480?

2021-07-07 01:59 UTC, LenaXmi commented on src/sass/layout/_footer.scss
> +  color: #b9b9b9;
Этот цвет тоже есть в переменной, измени, пожалуйста

2021-07-07 01:59 UTC, LenaXmi commented on src/partials/footer.html
> +        <svg class="logo__icon" width="128px" height="45px">
Измени, пожалуйста, лого

<a class="logo" href="./index.html">
  <p class="logo__top">
    Hell<svg class="logo__icon">
      <use href="./images/icons.svg#campfire"></use></svg
    >EN
  </p>
  <p class="logo__bottom"><span class="logo__bottom--accent">hellish </span>english</p>
</a>

.logo {
  &__top {
    font-weight: 800;
    font-size: 26px;
    line-height: 1.23;
    letter-spacing: 0.04em;
    color: $boldTextColor;
  }
  &__icon {
    width: 22px;
    height: 30px;
    color: $accentTextColor;
  }
  &__bottom {
    font-weight: 700;
    font-size: 8px;
    line-height: 10px;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    color: $boldTextColor;

    &--accent {
      color: $accentTextColor;
    }
  }
}

2021-07-07 11:10 UTC, Halishchev commented on src/sass/layout/_footer.scss
> +  color: #b9b9b9;
этот цвет по умолчанию, я просто забыл его убрать, исправил

2021-07-07 11:13 UTC, Halishchev commented on src/partials/footer.html
> +        <svg class="logo__icon" width="128px" height="45px">
там не ровное лого и при адаптиве часть улетает, у меня е особо много времени фиксить это

2021-07-07 11:14 UTC, Halishchev commented on src/sass/layout/_footer.scss
> +  @media screen and (max-width: 460px) {
до 460 оно нормально влазит, потом улетает,  исправил на 479

2021-07-07 11:15 UTC, Halishchev commented on src/sass/layout/_footer.scss
> +    transition: color $animation;
точно, исправил)

2021-07-07 16:46 UTC, LenaXmi approved these changes

2021-07-07 16:48 UTC, LenaXmi approved these changes

2021-07-07 21:58 UTC, DimaLitvinenko approved these changes

2021-07-07 23:07 UTC, merged

2021-07-07 23:14 UTC, zaktitov commented on src/sass/layout/_footer.scss
> +  @media screen and (max-width: 768px) {
привет)) Если я правильно тебя понял, то точка перелома с телефона на плашет имелась ввиду здесь, то тогда по идее должно быть на 1 пиксель меньше макс видс, если ты НЕ через мин видс указываешь

2021-07-07 23:14 UTC, zaktitov commented on src/sass/layout/_footer.scss
> +  @media screen and (max-width: 1360px) {
вроде договорились 1366 , как в ТЗ

2021-07-07 23:14 UTC, zaktitov commented on src/sass/layout/_footer.scss
> +  @media screen and (max-width: 768px) {
там что ниже , точно так же написано. Если я что то не так понял, извиняюсь