Feature/benefits
LenaXmi/calc-2-fantasticFour- pull request #4
Opened 2021-07-06 22:20 UTC by pavlykravlyk

2021-07-06 23:43 UTC, DimaLitvinenko approved these changes
супер

2021-07-07 04:54 UTC, LenaXmi requested changes

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_benefits.scss
> +  background-image: linear-gradient(to bottom, #111518 65%, #ffffff 65%, #ffffff 100%);
Я в своей секции цвета прописывала через переменные и с другим процентным соотношением. Нужно будет обсудить это, чтобы у нас градиенты одинаково выглядели

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_benefits.scss
> +    color: #ffffff;
Добавь, пожалуйста, цвет через переменную

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_benefits.scss
> +    background-color: #ffffff;
Переменная)

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_benefits.scss
> +    line-height: 20px;
Интерлиньяж через множитель укажи, пожалуйста

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_benefits.scss
> +    color: #111518;
Переменная

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_program.scss
> +      line-height: 28px;
Множитель

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_program.scss
> +  line-height: 20px;
Множитель

2021-07-07 04:54 UTC, LenaXmi commented on src/sass/layout/_program.scss
> +    line-height: 28px;
Множитель

2021-07-07 16:45 UTC, LenaXmi approved these changes

2021-07-07 16:45 UTC, merged