Додає розмітку і стилі
LenaXmi/calc-2-fantasticFour- pull request #5
Opened 2021-07-06 22:25 UTC by pavlykravlyk

2021-07-06 23:41 UTC, DimaLitvinenko approved these changes
всё отлично

2021-07-07 04:43 UTC, LenaXmi requested changes

2021-07-07 04:43 UTC, LenaXmi commented on src/sass/layout/_program.scss
> +      line-height: 28px;
Паш, кажись забыл интерлиньяж через множитель прописать.

2021-07-07 04:43 UTC, LenaXmi commented on src/sass/layout/_program.scss
> +    line-height: 28px;
И здесь тоже множитель)

2021-07-07 16:44 UTC, LenaXmi approved these changes

2021-07-07 16:44 UTC, merged