Section/about
LenaXmi/calc-2-fantasticFour- pull request #9
Opened 2021-07-07 20:47 UTC by MaksymTykhonskyi

2021-07-07 22:07 UTC, DimaLitvinenko requested changes

2021-07-07 22:07 UTC, DimaLitvinenko commented on src/sass/layout/_about.scss
> +        @media screen and (min-width: 768px) {
почему пустой медиа? забыл может font size line height для таблетки?

2021-07-07 22:07 UTC, DimaLitvinenko commented on src/sass/layout/_about.scss
> +            @media screen and (min-width: 768px) {
тоже самое пустой медиа

2021-07-07 22:07 UTC, DimaLitvinenko commented on src/sass/layout/_about.scss
> +    &__text-paragraph:before {
исправь бифор должен быть ::before

2021-07-07 23:06 UTC, zaktitov commented on src/sass/layout/_about.scss
> +    &__text-paragraph:before {
🥇

2021-07-08 17:22 UTC, MaksymTykhonskyi commented on src/sass/layout/_about.scss
> +        @media screen and (min-width: 768px) {
нет там просто проверял марджин и не удалил

2021-07-08 17:33 UTC, LenaXmi approved these changes

2021-07-08 18:30 UTC, DimaLitvinenko approved these changes

2021-07-08 18:33 UTC, merged

2021-07-08 21:11 UTC, LenaXmi reviewed
ок